### ISSUE TITLE
Cached values returned from EncodeUint64 are dangerous.

### ISSUE THREAD

**Issue by cube2222** [tetratelabs/wabin#9]
Hey!
Let me start by saying that your work on wazero is amazing!

Now to the point, leb128.EncodeUint64 returns a cached value if the argument is less than `0x80` in order to avoid allocations.

However, that means that you can accidentally break the cache (and future usages of the function) by modifying the slice you receive from the function, and that is **really** unexpected.

I wrote a function for writing fully-padded leb128 uint32 values when experimenting with relocatable wasm object files, something akin to this:
```go
func encodePaddedLeb128(value uint32) []byte {
	encodedBytes := leb128.EncodeUint32(value)
	for len(encodedBytes) < 5 {
		encodedBytes[len(encodedBytes)-1] |= 0x80
		encodedBytes = append(encodedBytes, 0)
	}
	return encodedBytes
}
```
and this function, quite unexpectedly, broke the leb128.EncodeUint32 function, which then broke the wabin package wasm module encoding functionality.

Moreover, this was quite the fun thing to debug, as in another place in the code I was taking a valid wasm module, decoding it, then encoding it back, and writing it to a file (I was sanity-check debugging) and that was breaking, when trying to decode the output once again, due to the internally broken leb128 encoding function.

I think it'd be worth it either removing the caching functionality, or spelling it out clearly in the function comment, that the returned slice is not to be modified.

Cheers!

**Comment by codefromthecrypt** [comment]
Thanks for elaborating on why this was painful. We didn't audit the codebase before extracting it for traps like this.. apologies!

While in the wazero-internal copy we probably will keep the cache, I can see the sense in removing it for wabin, which is for routine use. Want to raise a PR to help avoid someone else tripping?

**Comment by cube2222** [comment]
@codefromthecrypt Sure thing! Here's the PR: https://github.com/tetratelabs/wabin/pull/10
